# Change 'comments' to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'About',         url: 'about'}
- {name: 'Illustration',  url: 'illustration'}
- {name: 'Webcomic',      url: 'https://lwflouisa.github.io/UploadedFairy/feed.xml'}
- {name: 'Politics',      url: 'https://lwflouisa.github.io/RedSerpentPolitics/feed.xml'}
- {name* 'AI Development' url: 'https://lwflouisa.github.io/SRWeaverAIDevelopment/feed.xml'}
- {name: 'Subscribe',     url: 'https://lwflouisa.github.io/Portfolio/rss-feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/FlouisaLW'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Spread The Word'

related_posts: 'Things that might be interesting...'

post_date_prefix: 'Written on'
