# Change 'comments' to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'About',             url: 'about'}
- {name: 'Art Tools',         url: 'arttools'}
- {name: 'Illustration',      url: 'illustration'}
- {name: 'Channel',           url: 'channel'}
- {name: 'Social',            url: 'social'}
- {name: 'Feeds',             url: 'feeds'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter',   link:              'https://twitter.com/FlouisaLW'}
- {icon: 'pinterest', link:    'https://www.pinterest.com/lwflouisa0808'}
- {icon: 'facebook',  link: 'https://www.facebook.com/HistoryOfEsfiomi/'}
- {icon: 'ello',  link:                      'https://ello.co/lwflouisa'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Spread The Word'

related_posts: 'Other information...'

post_date_prefix: 'Written on'
